server:
  port: 9090
spring:
  application:
    name: Blog App
    serverURL: http://localhost:9090/unlock?email=
  datasource:
    url: jdbc:mysql://viaduct.proxy.rlwy.net:24060/blog_app?createDatabaseIfNotExist=true
    username: root
    password: uDQXktXHBMNSNUhIJWrBgqYZSijBYDFz
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: -- USER NAME --
    password: -- PASSWORD --
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
       smtp:
        auth: true
        starttls:
          enable: true
